### ISSUE TITLE
Scroll Balken beim Align beachten

### ISSUE THREAD

**Issue by nichoio** [sebdei/hackercv#14]
Wenn vertikaler Scrollbalken hinzukommt, verschiebt sich der gesamte Content leicht. Sieht unschön aus.

**Comment by sebdei** [comment]
Ist mir auch schon aufgefallen. Ich habe darauf gehofft, wir lösen das durch hinzufügen von content. Beim nochmal drüber nachdenken finde ich aber ein `overflow: scroll` an z.B. `.app` oder `body`  besser.
